### ISSUE TITLE
tls-czone.hpp deleted but still referenced in code

### ISSUE THREAD

**Issue by cburschka** [Malvineous/libgamegraphics#4]
Along with a few other files that seem to have been removed or refactored, like img-cga.hpp and camoto/gamegraphics/palettetable.hpp.

Is the master branch currently broken due to work in progress, or is this an oversight?

(I tried to build v1.2 but ran into problems related to C++-11.)

**Comment by cburschka** [comment]
Update: The 1.2 issues were only caused by accidentally using the wrong version of libgamecommon. Looks like I can build the whole thing (v1.2 that is) correctly.

(Of course, I now get the Malvineous/camoto-studio#1 error, but that's unrelated. :) )

**Comment by Malvineous** [comment]
Thanks I will check this.  The `master` branch has undergone a huge rewrite, but it has been completed for libgamegraphics so what you've encountered is likely an oversight.

If you want to use the Camoto Studio GUI then you'll have to stick with the `v1.x` branch as there is no GUI yet (or libgamemusic) that works with v2.0 (the `master` branches).  `v1.x` works for everything, however it's missing support for a few games and I'm not planning any further work on it.  There's a bit more background at the top of http://www.shikadi.net/camoto

**Comment by cburschka** [comment]
Thanks for the explanation! I'm mostly after extracting some TIM resource archives, so it looks like `gamearch` is all I need right now.

**Comment by Malvineous** [comment]
Yes if you're after TIM data, `gamearch` is the only program that will be useful to you, and the `master` branch will be fine.  None of the other apps/libraries support any TIM data (yet!)  If you manage to reverse engineer any TIM formats, please consider putting your findings on the [ModdingWiki](http://www.shikadi.net/moddingwiki/)!

I'll leave this issue open until I've resolved the problems with the missing files completely.  Almost there, but I've realised I still have to rewrite a couple more format handlers first.

**Comment by cburschka** [comment]
Thanks! That was going to be my next question. I'm puzzling over the format
of the .BMP files (which apparently aren't ordinary BMPs). If I manage to
get anywhere, I'll try to contribute!

**Comment by Malvineous** [comment]
Just closing this issue now that the current git master branch compiles without any references to missing files.
